# When a commmit is pushed to the `main` branch deploy to production
name: Deploy to Production
on:
  push:
    branches:
      - main # TODO - this may need updating
jobs:
  production_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      # ... steps to build Shopify theme ...

      - name: Shopify Theme Actions
        uses: matthew-petrie/shopify-theme-actions@1.0.0
        with:
          ACTION: "DEPLOY"
          SHOPIFY_STORE_URL: ${{secrets.SHOPIFY_STORE_URL}}
          SHOPIFY_PASSWORD: ${{secrets.SHOPIFY_PASSWORD}}
          SHOPIFY_API_KEY: ${{secrets.SHOPIFY_API_KEY}}
          SHOPIFY_THEME_KIT_FLAGS: "dir=./dist,allowLive=true" # TODO - this may need updating
          SHOPIFY_THEME_ID: 12156 # TODO - THIS MUST BE UPDATED
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
