name: pull-request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
      - name: Jest Tests and Coverage
        uses: willcaul/jest-github-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run test_coverage"
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Prettify Code
      run: npm run format
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Build Code
      run: npm run build
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions